### ISSUE TITLE
テストを実行ごとに結果が変わる原因の調査・修正

### ISSUE THREAD

**Issue by TheSelfAtu** [TheSelfAtu/keep-growing-kusa#31]
# 概要
- 現状、テストを実行すると同じテストでも成功する場合と失敗する場合がある。
その原因の調査と修正をする。

# タスク
- [x] テストの失敗原因の特定
- [x] 原因の修正

**Comment by TheSelfAtu** [comment]
調査結果
- create⇒findの順番は正しい
-

**Comment by TheSelfAtu** [comment]
## postgresqlのログ
docker-compose.ymlのlog_statement=allなどの設定値は
postgresqlコンテナ内の postgresql.confには反映されていない。
しかし、show all ; で表示されたpostgresqlの設定値には反映されている

docker-compose.yml
```
services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"
```
postgresql.conf
```
#log_statement = 'none'                 # none, ddl, mod, all
```


show all ;の出力結果
![image](https://user-images.githubusercontent.com/43713568/202880257-4111e604-abd6-4cfa-87f1-a1ec714750fa.png)
